# Generated by Django 5.1.7 on 2025-03-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_user'),
    ]

    operations = [
    ]
