# Generated by Django 5.1.7 on 2025-03-29 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_order_user_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer')], default='farmer', max_length=20),
        ),
    ]
