# Generated by Django 5.1.7 on 2025-03-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20250331_1342'),
    ]

    operations = [
    ]
